name: C Program Workflow

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build and Run C Program
              run: |
                  cd src
                  gcc -o App HospitalManagement1024.c
                  ./App
